import { type MenuItem, type Category } from './types';

export const categories: { id: Category; name: string }[] = [
  { id: 'hot-drinks', name: 'نوشیدنی‌های گرم' },
  { id: 'cold-drinks', name: 'نوشیدنی‌های سرد' },
  { id: 'meals', name: 'غذاها' },
  { id: 'desserts', name: 'دسرها' },
];

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: 'کباب کوبیده',
    description: 'دو سیخ کباب کوبیده گوشت مخلوط گوسفندی و گوساله با گوجه کبابی و نان تازه',
    price: 250000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'kebab koobideh',
    category: 'meals',
    featured: true,
  },
  {
    id: 2,
    name: 'جوجه کباب',
    description: 'یک سیخ جوجه کباب زعفرانی با استخوان، به همراه برنج ایرانی و کره محلی',
    price: 220000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'joojeh kebab',
    category: 'meals',
  },
  {
    id: 3,
    name: 'قورمه سبزی',
    description: 'خورشت سنتی قورمه سبزی با گوشت گوسفندی، لوبیا و سبزیجات معطر',
    price: 180000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'ghormeh sabzi',
    category: 'meals',
  },
  {
    id: 4,
    name: 'قهوه اسپرسو',
    description: 'یک شات اسپرسوی غلیظ و معطر از بهترین دانه‌های قهوه عربیکا',
    price: 60000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'espresso coffee',
    category: 'hot-drinks',
    featured: true,
  },
  {
    id: 5,
    name: 'کاپوچینو',
    description: 'ترکیبی عالی از اسپرسو، شیر بخار داده شده و فوم شیر غلیظ',
    price: 75000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'cappuccino art',
    category: 'hot-drinks',
  },
  {
    id: 6,
    name: 'چای سیاه',
    description: 'چای سیاه ممتاز ایرانی، دم کشیده به روش سنتی با طعم گس و دلنشین',
    price: 40000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'black tea',
    category: 'hot-drinks',
  },
  {
    id: 7,
    name: 'آب پرتقال طبیعی',
    description: 'آب پرتقال تازه و طبیعی، سرشار از ویتامین C',
    price: 70000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'orange juice',
    category: 'cold-drinks',
  },
  {
    id: 8,
    name: 'شیک شکلات',
    description: 'شیک شکلات غلیظ و خنک با بستنی وانیلی و سس شکلات',
    price: 90000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'chocolate milkshake',
    category: 'cold-drinks',
  },
  {
    id: 9,
    name: 'کیک شکلاتی',
    description: 'برشی از کیک شکلاتی خانگی، غرق در گاناش شکلات تلخ',
    price: 85000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'chocolate cake',
    category: 'desserts',
    featured: true,
  },
  {
    id: 10,
    name: 'باقلوا',
    description: 'باقلوای سنتی پر شده با پسته و گردو، آغشته به شهد زعفران و گلاب',
    price: 95000,
    image: 'https://placehold.co/400x300.png',
    aiHint: 'baklava dessert',
    category: 'desserts',
  },
];
